config = {
    "N_SEEDS": 1,
    # "ENV_NAME": "Whirlpool",
    "ENV_NAME": "FourRooms-misc",
    "GAMMA": 0.99,
    "k": 16,
    "MAX_STEPS_IN_EPISODE": 1e6,
    "LAYER_NORM": False,
    "LR": 0.0003,
    "LR_END": None,
    "ACTOR_LR": 0.0003,
    "ACTOR_LR_END": None,
    "NUM_ENVS": 1,
    "NUM_STEPS": 1,
    "TOTAL_TIMESTEPS": 1000,
    "NUM_EPOCHS": 1,
    "MINIBATCH_SIZE": 1,
    # "NUM_ENVS": 1,
    # "NUM_STEPS": 1,
    # "TOTAL_TIMESTEPS": 1000,
    # "NUM_EPOCHS": 1,
    # "MINIBATCH_SIZE": 1,
    "VALUE_LAMBDA": 1.0,
    "GAE_LAMBDA": 0.5,
    "CLIP_EPS": 0.05,
    "VF_CLIP": 0.5,
    "DIRICHLET_COEF_START": 1.0,
    "DIRICHLET_COEF_END": 1.0,
    "CLIP_DIRICHLET": False,
    "DIRICHLET_CLIP_TYPE": "max",
    "VF_CLIP_MAGNITUDE": False,
    "ENT_COEF": 0.01,
    "VF_COEF": 0.5,
    "MAX_GRAD_NORM": 1.0,
    "NETWORK_TYPE": "cnn",
    "NORMALIZE_OBS": False,
    "CALC_TRUE_VALUES": True,
    "BATCH_SIZE": 104,
    # For the fixed:
    # 'MODEL_LOAD_DIR': "cont",
    "MODEL_LOAD_DIR": "short_run",
    "LOG_FEATURE_METRICS": False,
}
